# Image taken from https://github.com/turlucode/ros-docker-gui
# but these are not pused
FROM ghcr.io/netdrones/ros-melodic:cpu

SHELL ["/bin/bash" , "-ueo", "pipefail", "-c"]

ARG DEBIAN_FRONTEND=noninteractive

# to allow small update pin only to major.minor.sub version
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gnupg2="2.2.*" \
        curl="7.58.*" \
        lsb-core="9.2017*" \
        vim="2:8.0*" \
        wget="1.19.*" \
        python-pip="9.0.1*" \
        libpng16-16=1.6.* \
        libjpeg-turbo8=1.5.* \
        libtiff5="4.0.*" && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        x11-apps="7.7*" \
        # Base tools
        cmake="3.10.2-*" \
        build-essential="12.4*" \
        git="1:2.17.*" \
        unzip="6.0-*" \
        pkg-config="0.29.1-*" \
        python-dev="2.7.15*" \
        # OpenCV dependencies
        python-numpy="1:1.13.3-*" \
        # Pangolin dependencies
        libgl1-mesa-dev="20.0.8-*" \
        libglew-dev="2.0.0-*" \
        libpython2.7="2.7.17-*" \
        libeigen3-dev="3.3.4-*" \
        apt-transport-https="1.6.14*" \
        ca-certificates="20211016*" \
        software-properties-common="0.96.24.*" && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl -fsSL https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -
RUN add-apt-repository "deb https://download.sublimetext.com/ apt/stable/"
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        sublime-text="41*" && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# # Build Pangolin
WORKDIR /tmp
RUN git clone -b v0.6 https://github.com/stevenlovegrove/Pangolin
WORKDIR /tmp/Pangolin/build
RUN cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-std=c++11 .. && \
    make -j"$(nproc)" && make install
WORKDIR /
RUN    rm -rf /tmp/Pangolin

COPY ros_entrypoint.sh /ros_entrypoint.sh
RUN chmod +x  /ros_entrypoint.sh
ENV ROS_DISTRO melodic
ENV LANG en_US.UTF-8

ENTRYPOINT ["/ros_entrypoint.sh"]

USER $USERNAME
# terminal colors with xterm
ENV TERM xterm
WORKDIR /ORB_SLAM3
CMD ["bash"]
